#!/system/bin/sh
echo "disabled" > /sys/class/leds/d601:B/device/engine1_mode
echo "disabled" > /sys/class/leds/d601:B/device/engine2_mode
echo "disabled" > /sys/class/leds/d601:B/device/engine3_mode
echo "disabled" > /sys/class/leds/d604:B/device/engine1_mode
echo "disabled" > /sys/class/leds/d604:B/device/engine2_mode
echo "disabled" > /sys/class/leds/d604:B/device/engine3_mode
echo "disabled" > /sys/class/leds/d610:B/device/engine1_mode
echo "disabled" > /sys/class/leds/d610:B/device/engine2_mode
echo "disabled" > /sys/class/leds/d610:B/device/engine3_mode
echo "disabled" > /sys/class/leds/d607:B/device/engine1_mode
echo "disabled" > /sys/class/leds/d607:B/device/engine2_mode
echo "disabled" > /sys/class/leds/d607:B/device/engine3_mode
echo 0 > /sys/class/leds/d601:G/brightness
echo 0 > /sys/class/leds/d602:G/brightness
echo 0 > /sys/class/leds/d603:G/brightness
echo 0 > /sys/class/leds/d604:G/brightness
echo 0 > /sys/class/leds/d605:G/brightness
echo 0 > /sys/class/leds/d606:G/brightness
echo 0 > /sys/class/leds/d607:G/brightness
echo 0 > /sys/class/leds/d608:G/brightness
echo 0 > /sys/class/leds/d609:G/brightness
echo 0 > /sys/class/leds/d610:G/brightness
echo 0 > /sys/class/leds/d611:G/brightness
echo 0 > /sys/class/leds/d612:G/brightness
echo 0 > /sys/class/leds/d601:B/brightness
echo 0 > /sys/class/leds/d602:B/brightness
echo 0 > /sys/class/leds/d603:B/brightness
echo 0 > /sys/class/leds/d604:B/brightness
echo 0 > /sys/class/leds/d605:B/brightness
echo 0 > /sys/class/leds/d606:B/brightness
echo 0 > /sys/class/leds/d607:B/brightness
echo 0 > /sys/class/leds/d608:B/brightness
echo 0 > /sys/class/leds/d609:B/brightness
echo 0 > /sys/class/leds/d610:B/brightness
echo 0 > /sys/class/leds/d611:B/brightness
echo 0 > /sys/class/leds/d612:B/brightness
echo 0 > /sys/class/leds/d601:R/brightness
echo 0 > /sys/class/leds/d602:R/brightness
echo 0 > /sys/class/leds/d603:R/brightness
echo 0 > /sys/class/leds/d604:R/brightness
echo 0 > /sys/class/leds/d605:R/brightness
echo 0 > /sys/class/leds/d606:R/brightness
echo 0 > /sys/class/leds/d607:R/brightness
echo 0 > /sys/class/leds/d608:R/brightness
echo 0 > /sys/class/leds/d609:R/brightness
echo 0 > /sys/class/leds/d610:R/brightness
echo 0 > /sys/class/leds/d611:R/brightness
echo 0 > /sys/class/leds/d612:R/brightness
